#!/bin/sh

export NUC_TOOLS_DIR="$(dirname "$(readlink -f $0)")"
export PYTHONPATH="${PYTHONPATH}:.:${NUC_TOOLS_DIR}"

#python -m nuc_processing.NucProcess $*
python3 ${NUC_TOOLS_DIR}/nuc_tools.py $*
